# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cloud_title', models.CharField(default=b'new cloud', max_length=100, unique=True)),
                ('cloud_state', models.IntegerField(choices=[(0, b'RGB Color'), (1, b'Disco Mode'), (2, b'Blue Sky'), (3, b'Night Time'), (4, b'Overcast'), (5, b'Golden'), (6, b'Snow'), (7, b'Lightning'), (8, b"What it's doing outside")], default=8)),
                ('cloud_rgb', models.CharField(default=b'#ffffff', max_length=7)),
            ],
        ),
    ]
