# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 22:33
from __future__ import unicode_literals

import CloudApi.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='cloud_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=CloudApi.models._slug_default_, editable=False, max_length=100, populate_from=b'cloud_title', unique=True),
        ),
    ]
