# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 07:14
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApi', '0002_currentstate_cloud_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstate',
            name='position',
            field=geoposition.fields.GeopositionField(default="0, 0", max_length=42),
            preserve_default=False,
        ),
    ]
